--// This file was created by XHider v1.2 [https://discord.gg/hATuHQaQRb]

local fenv = getfenv()
local _ = fenv.fOW5yVEpLEgi1
local _ = fenv.K7TdzNMYhwyDn
local _ = fenv.FcKVMc90Ou8d
local _ = fenv.di1rBk6gho3SMH
local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")
local gui = Instance.new("ScreenGui")
gui.Name = "TTriDangZuesSplash"
gui.ResetOnSpawn = false
local playergui = Players.LocalPlayer:WaitForChild("PlayerGui")
gui.Parent = playergui
local label = Instance.new("TextLabel")
label.Size = UDim2.new(0, 500, 0, 120)
label.Position = UDim2.new(0.5, -250, 0.5, -60)
label.BackgroundTransparency = 1
label.Text = "TTri x DangZues"
label.TextColor3 = Color3.fromRGB(145, 85, 255)
label.TextSize = 60
label.Font = Enum.Font.GothamBlack
label.TextTransparency = 1
label.Parent = gui
local _v = task.wait(0.3)
local _v1 = TweenService:Create(label, TweenInfo.new(0.8, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {TextTransparency = 0})
local _v2 = _v1:Play()
local _v3 = _v1.Completed:Wait()
local _v = task.wait(1)
local _v4 = TweenService:Create(label, TweenInfo.new(0.5, Enum.EasingStyle.Quad, Enum.EasingDirection.In), {TextTransparency = 1})
local _v5 = _v4:Play()
local _v6 = _v4.Completed:Wait()
local _v7 = gui:Destroy()
local _v = task.spawn(function(...)
    local _v11 = Players.LocalPlayer.Character:FindFirstChild("Humanoid")
    _v11.MaxHealth = math.huge
    _v11.Health = math.huge
    local _v12 = _v11:SetStateEnabled(Enum.HumanoidStateType.Dead, false)
    local _v13 = RunService.RenderStepped:Wait()
    local _v14 = Players.LocalPlayer.Character:FindFirstChild("Humanoid")
    _v14.MaxHealth = math.huge
    _v14.Health = math.huge
    local _v15 = _v14:SetStateEnabled(Enum.HumanoidStateType.Dead, false)
    local _v16 = RunService.RenderStepped:Wait()
    local _v17 = Players.LocalPlayer.Character:FindFirstChild("Humanoid")
    _v17.MaxHealth = math.huge
    _v17.Health = math.huge
    local _v18 = _v17:SetStateEnabled(Enum.HumanoidStateType.Dead, false)
    local _v19 = RunService.RenderStepped:Wait()
end)
local _v = task.spawn(function(...)
    workspace.CurrentCamera.CameraSubject = _v300013
    workspace.CurrentCamera.CameraType = Enum.CameraType.Custom
    workspace.CurrentCamera.CameraSubject = _v300015
    workspace.CurrentCamera.CameraType = Enum.CameraType.Custom
    workspace.CurrentCamera.CameraSubject = _v300017
    workspace.CurrentCamera.CameraType = Enum.CameraType.Custom
end)
local _v = task.spawn(function(...)
    task.wait(1)
    local _v550013 = Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
    Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(Vector3.new(541.90795898438, 70.574433237305, -364.46081542969))
    local _ = fenv.XpmotAsQ83dt
end)
local onCharacterAdded = Players.LocalPlayer.CharacterAdded:Connect(function(character)
    local humanoid = character:WaitForChild("Humanoid")
    humanoid.MaxHealth = math.huge
    humanoid.Health = math.huge
    local _v550014 = humanoid:SetStateEnabled(Enum.HumanoidStateType.Dead, false)
    task.wait(1)
    local _v550015 = character:FindFirstChild("HumanoidRootPart")
    character.HumanoidRootPart.CFrame = CFrame.new(Vector3.new(541.90795898438, 70.574433237305, -364.46081542969))
    local _ = fenv.p9baj3iV13Dt
end)
local onHeartbeat = RunService.Heartbeat:Connect(function(deltaTime)
    local _v550016 = Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
    local _v550017 = Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
end)
gui.Name = "TTriDangZuesGUI"
gui.ResetOnSpawn = false
gui.IgnoreGuiInset = true
gui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
gui.Parent = playergui
local frame = Instance.new("Frame")
frame.Size = UDim2.new(0, 550, 0, 360)
frame.Position = UDim2.new(0.5, -275, 0.5, -180)
frame.BackgroundColor3 = Color3.fromRGB(9, 9, 14)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
local _ = fenv.A7JVxmmZDbyDs
frame.Parent = gui
local corner = Instance.new("UICorner")
corner.CornerRadius = UDim.new(0, 13)
local _ = fenv.CGgZWuZN8U91Pi
corner.Parent = frame
local uistroke = Instance.new("UIStroke")
uistroke.Color = Color3.fromRGB(55, 42, 80)
uistroke.Transparency = 0.15
local _ = fenv.ebR5LHq63iy2
uistroke.Thickness = 1
uistroke.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 45)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0, 160, 1, 0)
label.Position = UDim2.new(0, 14, 0, 0)
label.BackgroundTransparency = 1
label.Text = "⚡ TTRI x DANGZUES"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.TextSize = 14
label.Font = Enum.Font.GothamBold
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(0, 90, 0, 24)
label.Position = UDim2.new(1, -160, 0.5, -12)
label.BackgroundColor3 = Color3.fromRGB(17, 34, 24)
label.Text = "\xe2\x97\x8f ONLINE"
label.TextColor3 = Color3.fromRGB(70, 215, 125)
label.TextSize = 9
label.Font = Enum.Font.GothamBold
label.Parent = frame
corner.CornerRadius = UDim.new(0, 7)
corner.Parent = label
local button = Instance.new("TextButton")
button.Size = UDim2.new(0, 28, 0, 28)
button.Position = UDim2.new(1, -62, 0.5, -14)
button.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
button.Text = "\xe2\x80\x94"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.TextSize = 15
button.Font = Enum.Font.GothamBold
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 7)
corner.Parent = button
button.Size = UDim2.new(0, 40, 0, 40)
button.Position = UDim2.new(1, -48, 0.5, -20)
button.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
button.Text = "A"
button.TextColor3 = Color3.fromRGB(255, 0, 0)
button.TextSize = 22
button.Font = Enum.Font.GothamBold
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 0)
corner.Parent = button
frame.Size = UDim2.new(0, 125, 1, -45)
frame.Position = UDim2.new(0, 0, 0, 45)
frame.BackgroundColor3 = Color3.fromRGB(13, 13, 20)
frame.BorderSizePixel = 0
frame.Parent = frame
local layout = Instance.new("UIListLayout")
layout.Padding = UDim.new(0, 5)
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Parent = frame
local uipadding = Instance.new("UIPadding")
uipadding.PaddingTop = UDim.new(0, 10)
uipadding.PaddingLeft = UDim.new(0, 8)
uipadding.PaddingRight = UDim.new(0, 8)
uipadding.Parent = frame
frame.Size = UDim2.new(1, -140, 1, -55)
frame.Position = UDim2.new(0, 140, 0, 50)
frame.BackgroundTransparency = 1
frame.Parent = frame
frame.Name = "HOME"
frame.Size = UDim2.new(1, 0, 1, 0)
frame.BackgroundTransparency = 1
frame.Visible = false
frame.Parent = frame
layout.Padding = UDim.new(0, 8)
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Parent = frame
uipadding.PaddingRight = UDim.new(0, 5)
uipadding.PaddingBottom = UDim.new(0, 5)
uipadding.Parent = frame
local _ = fenv.Weh688A94Ey9z0
frame.Name = "MAIN"
frame.Size = UDim2.new(1, 0, 1, 0)
frame.BackgroundTransparency = 1
frame.Visible = false
frame.Parent = frame
layout.Padding = UDim.new(0, 8)
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Parent = frame
uipadding.PaddingRight = UDim.new(0, 5)
uipadding.PaddingBottom = UDim.new(0, 5)
uipadding.Parent = frame
frame.Name = "FARM"
frame.Size = UDim2.new(1, 0, 1, 0)
frame.BackgroundTransparency = 1
frame.Visible = false
frame.Parent = frame
layout.Padding = UDim.new(0, 8)
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Parent = frame
uipadding.PaddingRight = UDim.new(0, 5)
uipadding.PaddingBottom = UDim.new(0, 5)
uipadding.Parent = frame
frame.Name = "DEFENSE"
frame.Size = UDim2.new(1, 0, 1, 0)
frame.BackgroundTransparency = 1
frame.Visible = false
frame.Parent = frame
layout.Padding = UDim.new(0, 8)
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Parent = frame
uipadding.PaddingRight = UDim.new(0, 5)
uipadding.PaddingBottom = UDim.new(0, 5)
uipadding.Parent = frame
frame.Name = "SETTING"
frame.Size = UDim2.new(1, 0, 1, 0)
frame.BackgroundTransparency = 1
frame.Visible = false
frame.Parent = frame
layout.Padding = UDim.new(0, 8)
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Parent = frame
uipadding.PaddingRight = UDim.new(0, 5)
uipadding.PaddingBottom = UDim.new(0, 5)
uipadding.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 45)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(1, 0, 0, 24)
label.BackgroundTransparency = 1
label.Text = "HOME"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamBold
label.TextSize = 19
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, 0, 0, 18)
label.Position = UDim2.new(0, 0, 0, 25)
label.BackgroundTransparency = 1
label.Text = (Welcome back,  .. Players.LocalPlayer.DisplayName)
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 10
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
local _ = fenv["4D03V31Bx6iF5"]
frame.Size = UDim2.new(1, 0, 0, 65)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
local _ = fenv.fq6sA4tr0rb9CB
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -24, 0, 20)
label.Position = UDim2.new(0, 12, 0, 7)
label.BackgroundTransparency = 1
label.Text = "SERVER STATUS"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamBold
label.TextSize = 11
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -24, 0, 18)
label.Position = UDim2.new(0, 12, 0, 32)
label.BackgroundTransparency = 1
local _v8 = Players:GetPlayers()
label.Text = "\xe2\x97\x8f Connected    Players: 0"
label.TextColor3 = Color3.fromRGB(70, 215, 125)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 65)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -24, 0, 20)
label.Position = UDim2.new(0, 12, 0, 7)
label.BackgroundTransparency = 1
label.Text = "PLAYER STATUS"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamBold
label.TextSize = 11
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -24, 0, 18)
label.Position = UDim2.new(0, 12, 0, 32)
label.BackgroundTransparency = 1
label.Text = (Players.LocalPlayer.Name .. (  |  ID:  .. Players.LocalPlayer.UserId))
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 45)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(1, 0, 0, 24)
label.BackgroundTransparency = 1
label.Text = "MAIN"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamBold
label.TextSize = 19
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, 0, 0, 18)
label.Position = UDim2.new(0, 0, 0, 25)
label.BackgroundTransparency = 1
label.Text = "Egg stealing controls"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 10
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 55)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -75, 0, 22)
label.Position = UDim2.new(0, 12, 0, 6)
label.BackgroundTransparency = 1
label.Text = "Auto Steal Random Egg"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -75, 0, 17)
label.Position = UDim2.new(0, 12, 0, 29)
label.BackgroundTransparency = 1
label.Text = "Random egg selection"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 42, 0, 22)
button.Position = UDim2.new(1, -54, 0.5, -11)
button.BackgroundColor3 = Color3.fromRGB(38, 38, 50)
button.Text = ""
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = button
frame.Size = UDim2.new(0, 16, 0, 16)
frame.Position = UDim2.new(0, 3, 0.5, -8)
frame.BackgroundColor3 = Color3.fromRGB(175, 175, 185)
frame.Parent = button
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = frame
local onClick = button.MouseButton1Click:Connect(function()
    local _v550018 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {BackgroundColor3 = Color3.fromRGB(145, 85, 255)})
    local _v550019 = _v550018:Play()
    local udim2 = TweenService:Create(frame, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {Position = UDim2.new(1, -19, 0.5, -8)})
    local _v550020 = udim2:Play()
    task.spawn(function(...) end)
    local _ = fenv.vBqahKx6WqmS
    local _ = fenv.uWftUslUuTi0
end)
local _ = fenv["0DP8nvPrCpA8"]
frame.Size = UDim2.new(1, 0, 0, 55)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -75, 0, 22)
label.Position = UDim2.new(0, 12, 0, 6)
label.BackgroundTransparency = 1
label.Text = "Auto Steal Best Egg"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -75, 0, 17)
label.Position = UDim2.new(0, 12, 0, 29)
label.BackgroundTransparency = 1
label.Text = "Target best egg"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 42, 0, 22)
button.Position = UDim2.new(1, -54, 0.5, -11)
button.BackgroundColor3 = Color3.fromRGB(38, 38, 50)
button.Text = ""
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = button
frame.Size = UDim2.new(0, 16, 0, 16)
frame.Position = UDim2.new(0, 3, 0.5, -8)
frame.BackgroundColor3 = Color3.fromRGB(175, 175, 185)
frame.Parent = button
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = frame
local onClick = button.MouseButton1Click:Connect(function()
    local _v550021 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {BackgroundColor3 = Color3.fromRGB(145, 85, 255)})
    local _v550022 = _v550021:Play()
    local udim2 = TweenService:Create(frame, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {Position = UDim2.new(1, -19, 0.5, -8)})
    local _v550023 = udim2:Play()
    task.spawn(function(...) end)
    local _ = fenv["2dglfF5JC8eo"]
end)
frame.Size = UDim2.new(1, 0, 0, 50)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(0.45, 0, 1, 0)
label.Position = UDim2.new(0, 12, 0, 0)
label.BackgroundTransparency = 1
label.Text = "Steal By Area"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0.5, -10, 0, 32)
button.Position = UDim2.new(0.5, 0, 0.5, -16)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.Text = "Forest  \xe2\x96\xbc"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 7)
corner.Parent = button
frame.Size = UDim2.new(0, 210, 0, 0)
frame.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
frame.BorderSizePixel = 0
frame.Visible = false
frame.ZIndex = 100
frame.Parent = gui
corner.CornerRadius = UDim.new(0, 8)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(145, 85, 255)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
local scrollingframe = Instance.new("ScrollingFrame")
scrollingframe.Size = UDim2.new(1, -4, 1, -4)
scrollingframe.Position = UDim2.new(0, 2, 0, 2)
scrollingframe.BackgroundTransparency = 1
scrollingframe.BorderSizePixel = 0
scrollingframe.ScrollBarThickness = 2
scrollingframe.ScrollBarImageColor3 = Color3.fromRGB(145, 85, 255)
scrollingframe.AutomaticCanvasSize = Enum.AutomaticSize.Y
scrollingframe.CanvasSize = UDim2.new()
scrollingframe.ZIndex = 101
scrollingframe.Parent = frame
layout.Padding = UDim.new(0, 1)
layout.Parent = scrollingframe
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Forest"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y)
    local _v550024 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {BackgroundColor3 = Color3.fromRGB(145, 85, 255)})
    local _v550025 = _v550024:Play()
    local _ = fenv.TibHQ5V6wCTfCu
end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y)
    local _v550026 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {BackgroundColor3 = Color3.fromRGB(24, 24, 35)})
    local _ = fenv.plO6Wo3tuMTb3
end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Forest  \xe2\x96\xbc"
    frame.Visible = false
    local _ = fenv.EaKlliZnWqUit
    local _ = fenv.QDzcGy1218GPE
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Desert"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y)
    local _v550030 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {BackgroundColor3 = Color3.fromRGB(24, 24, 35)})
end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Desert  \xe2\x96\xbc"
    frame.Visible = false
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Snow"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y)
    local _v550034 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {BackgroundColor3 = Color3.fromRGB(24, 24, 35)})
end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Snow  \xe2\x96\xbc"
    frame.Visible = false
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Lake"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Lake  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Volcano"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Volcano  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Abyss Ocean"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Abyss Ocean  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Cosmic"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Cosmic  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Prehistoric"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Prehistoric  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Jungle"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Jungle  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Cherry Blossom"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Cherry Blossom  \xe2\x96\xbc"
end)
local onClick = button.MouseButton1Click:Connect(function()
    local _ = fenv.pAbjQ3FlfYl6
    local _ = fenv.l3K2cYZvfeYN
end)
local _ = fenv.BAhyR88NEJaH
frame.Size = UDim2.new(1, 0, 0, 50)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(0.45, 0, 1, 0)
label.Position = UDim2.new(0, 12, 0, 0)
label.BackgroundTransparency = 1
label.Text = "Steal By Rank"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0.5, -10, 0, 32)
button.Position = UDim2.new(0.5, 0, 0.5, -16)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.Text = "Common  \xe2\x96\xbc"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 7)
corner.Parent = button
frame.Size = UDim2.new(0, 210, 0, 0)
frame.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
frame.BorderSizePixel = 0
frame.Visible = false
frame.ZIndex = 100
frame.Parent = gui
corner.CornerRadius = UDim.new(0, 8)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(145, 85, 255)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
scrollingframe.Size = UDim2.new(1, -4, 1, -4)
scrollingframe.Position = UDim2.new(0, 2, 0, 2)
scrollingframe.BackgroundTransparency = 1
scrollingframe.BorderSizePixel = 0
scrollingframe.ScrollBarThickness = 2
scrollingframe.ScrollBarImageColor3 = Color3.fromRGB(145, 85, 255)
scrollingframe.AutomaticCanvasSize = Enum.AutomaticSize.Y
scrollingframe.CanvasSize = UDim2.new()
scrollingframe.ZIndex = 101
scrollingframe.Parent = frame
layout.Padding = UDim.new(0, 1)
layout.Parent = scrollingframe
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Common"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Common  \xe2\x96\xbc"
    local _ = fenv.OsD2njCywZipZ
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Uncommon"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Uncommon  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Rare"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Rare  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Epic"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Epic  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Legendary"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Legendary  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Mythical"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Mythical  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Cosmic"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Cosmic  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Secret"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Secret  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Eternal"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Eternal  \xe2\x96\xbc"
end)
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(24, 24, 35)
button.BackgroundTransparency = 0
button.BorderSizePixel = 0
button.Text = "Divine"
button.TextColor3 = Color3.fromRGB(242, 242, 248)
button.Font = Enum.Font.Gotham
button.TextSize = 10
button.AutoButtonColor = false
button.ZIndex = 102
button.Parent = scrollingframe
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    button.Text = "Divine  \xe2\x96\xbc"
end)
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 45)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(1, 0, 0, 24)
label.BackgroundTransparency = 1
label.Text = "FARM"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamBold
label.TextSize = 19
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, 0, 0, 18)
label.Position = UDim2.new(0, 0, 0, 25)
label.BackgroundTransparency = 1
label.Text = "Training and garden controls"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 10
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 55)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -75, 0, 22)
label.Position = UDim2.new(0, 12, 0, 6)
label.BackgroundTransparency = 1
label.Text = "Auto Training"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -75, 0, 17)
label.Position = UDim2.new(0, 12, 0, 29)
label.BackgroundTransparency = 1
label.Text = "Automatic training"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 42, 0, 22)
button.Position = UDim2.new(1, -54, 0.5, -11)
button.BackgroundColor3 = Color3.fromRGB(38, 38, 50)
button.Text = ""
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = button
frame.Size = UDim2.new(0, 16, 0, 16)
frame.Position = UDim2.new(0, 3, 0.5, -8)
frame.BackgroundColor3 = Color3.fromRGB(175, 175, 185)
frame.Parent = button
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = frame
local onClick = button.MouseButton1Click:Connect(function()
    local udim2 = TweenService:Create(frame, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {Position = UDim2.new(1, -19, 0.5, -8)})
    local _v550106 = udim2:Play()
    local _ = fenv.farmToggles
end)
frame.Size = UDim2.new(1, 0, 0, 55)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -75, 0, 22)
label.Position = UDim2.new(0, 12, 0, 6)
label.BackgroundTransparency = 1
label.Text = "Auto Upgrade Training"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -75, 0, 17)
label.Position = UDim2.new(0, 12, 0, 29)
label.BackgroundTransparency = 1
label.Text = "Upgrade training"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 42, 0, 22)
button.Position = UDim2.new(1, -54, 0.5, -11)
button.BackgroundColor3 = Color3.fromRGB(38, 38, 50)
button.Text = ""
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = button
frame.Size = UDim2.new(0, 16, 0, 16)
frame.Position = UDim2.new(0, 3, 0.5, -8)
frame.BackgroundColor3 = Color3.fromRGB(175, 175, 185)
frame.Parent = button
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = frame
local onClick = button.MouseButton1Click:Connect(function()
    local udim2 = TweenService:Create(frame, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {Position = UDim2.new(1, -19, 0.5, -8)})
    local _v550109 = udim2:Play()
end)
frame.Size = UDim2.new(1, 0, 0, 55)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -75, 0, 22)
label.Position = UDim2.new(0, 12, 0, 6)
label.BackgroundTransparency = 1
label.Text = "Auto Upgrade Garden"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -75, 0, 17)
label.Position = UDim2.new(0, 12, 0, 29)
label.BackgroundTransparency = 1
label.Text = "Upgrade garden"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 42, 0, 22)
button.Position = UDim2.new(1, -54, 0.5, -11)
button.BackgroundColor3 = Color3.fromRGB(38, 38, 50)
button.Text = ""
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = button
frame.Size = UDim2.new(0, 16, 0, 16)
frame.Position = UDim2.new(0, 3, 0.5, -8)
frame.BackgroundColor3 = Color3.fromRGB(175, 175, 185)
frame.Parent = button
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = frame
local onClick = button.MouseButton1Click:Connect(function()
    local udim2 = TweenService:Create(frame, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {Position = UDim2.new(1, -19, 0.5, -8)})
    local _v550112 = udim2:Play()
end)
frame.Size = UDim2.new(1, 0, 0, 55)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -75, 0, 22)
label.Position = UDim2.new(0, 12, 0, 6)
label.BackgroundTransparency = 1
label.Text = "Auto Sell Full Egg"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -75, 0, 17)
label.Position = UDim2.new(0, 12, 0, 29)
label.BackgroundTransparency = 1
label.Text = "Sell when storage is full"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 42, 0, 22)
button.Position = UDim2.new(1, -54, 0.5, -11)
button.BackgroundColor3 = Color3.fromRGB(38, 38, 50)
button.Text = ""
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = button
frame.Size = UDim2.new(0, 16, 0, 16)
frame.Position = UDim2.new(0, 3, 0.5, -8)
frame.BackgroundColor3 = Color3.fromRGB(175, 175, 185)
frame.Parent = button
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 45)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(1, 0, 0, 24)
label.BackgroundTransparency = 1
label.Text = "DEFENSE"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamBold
label.TextSize = 19
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, 0, 0, 18)
label.Position = UDim2.new(0, 0, 0, 25)
label.BackgroundTransparency = 1
label.Text = "Combat settings"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 10
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 55)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -75, 0, 22)
label.Position = UDim2.new(0, 12, 0, 6)
label.BackgroundTransparency = 1
label.Text = "Kill Aura"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -75, 0, 17)
label.Position = UDim2.new(0, 12, 0, 29)
label.BackgroundTransparency = 1
label.Text = "Kill aura interface"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 42, 0, 22)
button.Position = UDim2.new(1, -54, 0.5, -11)
button.BackgroundColor3 = Color3.fromRGB(38, 38, 50)
button.Text = ""
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = button
frame.Size = UDim2.new(0, 16, 0, 16)
frame.Position = UDim2.new(0, 3, 0.5, -8)
frame.BackgroundColor3 = Color3.fromRGB(175, 175, 185)
frame.Parent = button
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = frame
local onClick = button.MouseButton1Click:Connect(function()
    local _ = fenv.CzbWVOMnrSigc
end)
frame.Size = UDim2.new(1, 0, 0, 55)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -75, 0, 22)
label.Position = UDim2.new(0, 12, 0, 6)
label.BackgroundTransparency = 1
label.Text = "Auto Equip Bat"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -75, 0, 17)
label.Position = UDim2.new(0, 12, 0, 29)
label.BackgroundTransparency = 1
label.Text = "Automatically equip bat"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 42, 0, 22)
button.Position = UDim2.new(1, -54, 0.5, -11)
button.BackgroundColor3 = Color3.fromRGB(38, 38, 50)
button.Text = ""
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = button
frame.Size = UDim2.new(0, 16, 0, 16)
frame.Position = UDim2.new(0, 3, 0.5, -8)
frame.BackgroundColor3 = Color3.fromRGB(175, 175, 185)
frame.Parent = button
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = frame
local onClick = button.MouseButton1Click:Connect(function()
    local _ = fenv.MNrzRTJ39jVKOS
end)
frame.Size = UDim2.new(1, 0, 0, 45)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(1, 0, 0, 24)
label.BackgroundTransparency = 1
label.Text = "SETTING"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamBold
label.TextSize = 19
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, 0, 0, 18)
label.Position = UDim2.new(0, 0, 0, 25)
label.BackgroundTransparency = 1
label.Text = "Interface settings"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 10
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 55)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -75, 0, 22)
label.Position = UDim2.new(0, 12, 0, 6)
label.BackgroundTransparency = 1
label.Text = "Animations"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -75, 0, 17)
label.Position = UDim2.new(0, 12, 0, 29)
label.BackgroundTransparency = 1
label.Text = "Interface animations"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 42, 0, 22)
button.Position = UDim2.new(1, -54, 0.5, -11)
button.BackgroundColor3 = Color3.fromRGB(38, 38, 50)
button.Text = ""
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = button
frame.Size = UDim2.new(0, 16, 0, 16)
frame.Position = UDim2.new(0, 3, 0.5, -8)
frame.BackgroundColor3 = Color3.fromRGB(175, 175, 185)
frame.Parent = button
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = frame
local onClick = button.MouseButton1Click:Connect(function()
    local _ = fenv.YCKrAuidfcOcyR
end)
frame.Size = UDim2.new(1, 0, 0, 55)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -75, 0, 22)
label.Position = UDim2.new(0, 12, 0, 6)
label.BackgroundTransparency = 1
label.Text = "Notifications"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -75, 0, 17)
label.Position = UDim2.new(0, 12, 0, 29)
label.BackgroundTransparency = 1
label.Text = "Show notifications"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 42, 0, 22)
button.Position = UDim2.new(1, -54, 0.5, -11)
button.BackgroundColor3 = Color3.fromRGB(38, 38, 50)
button.Text = ""
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = button
frame.Size = UDim2.new(0, 16, 0, 16)
frame.Position = UDim2.new(0, 3, 0.5, -8)
frame.BackgroundColor3 = Color3.fromRGB(175, 175, 185)
frame.Parent = button
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = frame
local onClick = button.MouseButton1Click:Connect(function()
    local _ = fenv.Tvqah0WeK0GMz
end)
frame.Size = UDim2.new(1, 0, 0, 55)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -75, 0, 22)
label.Position = UDim2.new(0, 12, 0, 6)
label.BackgroundTransparency = 1
label.Text = "Activity Logging"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -75, 0, 17)
label.Position = UDim2.new(0, 12, 0, 29)
label.BackgroundTransparency = 1
label.Text = "Save activity logs"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 42, 0, 22)
button.Position = UDim2.new(1, -54, 0.5, -11)
button.BackgroundColor3 = Color3.fromRGB(38, 38, 50)
button.Text = ""
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = button
frame.Size = UDim2.new(0, 16, 0, 16)
frame.Position = UDim2.new(0, 3, 0.5, -8)
frame.BackgroundColor3 = Color3.fromRGB(175, 175, 185)
frame.Parent = button
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = frame
local onClick = button.MouseButton1Click:Connect(function()
    local _ = fenv.knHbY2S2Q774
end)
frame.Size = UDim2.new(1, 0, 0, 55)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 27)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = frame
corner.CornerRadius = UDim.new(0, 9)
corner.Parent = frame
uistroke.Color = Color3.fromRGB(40, 40, 55)
uistroke.Transparency = 0.25
uistroke.Thickness = 1
uistroke.Parent = frame
label.Size = UDim2.new(1, -75, 0, 22)
label.Position = UDim2.new(0, 12, 0, 6)
label.BackgroundTransparency = 1
label.Text = "Performance Mode"
label.TextColor3 = Color3.fromRGB(242, 242, 248)
label.Font = Enum.Font.GothamSemibold
label.TextSize = 12
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Size = UDim2.new(1, -75, 0, 17)
label.Position = UDim2.new(0, 12, 0, 29)
label.BackgroundTransparency = 1
label.Text = "Reduce visual effects"
label.TextColor3 = Color3.fromRGB(145, 145, 160)
label.Font = Enum.Font.Gotham
label.TextSize = 9
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 42, 0, 22)
button.Position = UDim2.new(1, -54, 0.5, -11)
button.BackgroundColor3 = Color3.fromRGB(38, 38, 50)
button.Text = ""
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = button
frame.Size = UDim2.new(0, 16, 0, 16)
frame.Position = UDim2.new(0, 3, 0.5, -8)
frame.BackgroundColor3 = Color3.fromRGB(175, 175, 185)
frame.Parent = button
corner.CornerRadius = UDim.new(0, 20)
corner.Parent = frame
local onClick = button.MouseButton1Click:Connect(function()
    local _ = fenv.SfQCRQfYida8U
end)
button.Size = UDim2.new(1, 0, 0, 34)
button.BackgroundColor3 = Color3.fromRGB(13, 13, 20)
button.Text = "⌂  HOME"
button.TextColor3 = Color3.fromRGB(145, 145, 160)
button.Font = Enum.Font.GothamSemibold
button.TextSize = 10
button.TextXAlignment = Enum.TextXAlignment.Left
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 7)
corner.Parent = button
local onMouseEnter = button.MouseEnter:Connect(function(x, y)
    local _ = fenv.ndo0rO6qEr12
end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y)
    local _ = fenv.ZFe11dNv7y87V
end)
local onClick = button.MouseButton1Click:Connect(function()
    frame.Visible = false
    local _v550134 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {
    BackgroundColor3 = Color3.fromRGB(13, 13, 20),
    TextColor3 = Color3.fromRGB(145, 145, 160)
})
    frame.Visible = false
    local _v550136 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {
    BackgroundColor3 = Color3.fromRGB(13, 13, 20),
    TextColor3 = Color3.fromRGB(145, 145, 160)
})
    frame.Visible = false
    local _v550138 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {
    BackgroundColor3 = Color3.fromRGB(13, 13, 20),
    TextColor3 = Color3.fromRGB(145, 145, 160)
})
    local _ = fenv.wbz3h96InEje
    frame.Visible = true
    local _v550144 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {
    BackgroundColor3 = Color3.fromRGB(45, 30, 70),
    TextColor3 = Color3.fromRGB(242, 242, 248)
})
end)
local _ = fenv["3K6hFwdABQ6V"]
button.Size = UDim2.new(1, 0, 0, 34)
button.BackgroundColor3 = Color3.fromRGB(13, 13, 20)
button.Text = "⚡  MAIN"
button.TextColor3 = Color3.fromRGB(145, 145, 160)
button.Font = Enum.Font.GothamSemibold
button.TextSize = 10
button.TextXAlignment = Enum.TextXAlignment.Left
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 7)
corner.Parent = button
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    frame.Visible = true
    local _v550156 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {
    BackgroundColor3 = Color3.fromRGB(45, 30, 70),
    TextColor3 = Color3.fromRGB(242, 242, 248)
})
end)
button.Size = UDim2.new(1, 0, 0, 34)
button.BackgroundColor3 = Color3.fromRGB(13, 13, 20)
button.Text = "🥚  FARM"
button.TextColor3 = Color3.fromRGB(145, 145, 160)
button.Font = Enum.Font.GothamSemibold
button.TextSize = 10
button.TextXAlignment = Enum.TextXAlignment.Left
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 7)
corner.Parent = button
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    frame.Visible = true
    local _v550168 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {
    BackgroundColor3 = Color3.fromRGB(45, 30, 70),
    TextColor3 = Color3.fromRGB(242, 242, 248)
})
end)
button.Size = UDim2.new(1, 0, 0, 34)
button.BackgroundColor3 = Color3.fromRGB(13, 13, 20)
button.Text = "🛡  DEFENSE"
button.TextColor3 = Color3.fromRGB(145, 145, 160)
button.Font = Enum.Font.GothamSemibold
button.TextSize = 10
button.TextXAlignment = Enum.TextXAlignment.Left
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 7)
corner.Parent = button
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    frame.Visible = true
    local _v550180 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {
    BackgroundColor3 = Color3.fromRGB(45, 30, 70),
    TextColor3 = Color3.fromRGB(242, 242, 248)
})
end)
button.Size = UDim2.new(1, 0, 0, 34)
button.BackgroundColor3 = Color3.fromRGB(13, 13, 20)
button.Text = "⚙  SETTING"
button.TextColor3 = Color3.fromRGB(145, 145, 160)
button.Font = Enum.Font.GothamSemibold
button.TextSize = 10
button.TextXAlignment = Enum.TextXAlignment.Left
button.AutoButtonColor = false
button.Parent = frame
corner.CornerRadius = UDim.new(0, 7)
corner.Parent = button
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function()
    frame.Visible = true
    local _v550192 = TweenService:Create(button, TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {
    BackgroundColor3 = Color3.fromRGB(45, 30, 70),
    TextColor3 = Color3.fromRGB(242, 242, 248)
})
end)
frame.Visible = true
button.BackgroundColor3 = Color3.fromRGB(45, 30, 70)
button.TextColor3 = Color3.fromRGB(242, 242, 248)
local onInputBegan = frame.InputBegan:Connect(function(input, gameProcessed)
    local _ = fenv.LU1y1LxNF2fyoh
    local _ = fenv.fPTwqmBBHSYdEA
end)
local onChanged = UserInputService.InputChanged:Connect(function(input, gameProcessed)
    frame.Position = UDim2.new(frame.Position.X.Scale, (frame.Position.X.Offset + (input.Position - input.Position).X), frame.Position.Y.Scale, (frame.Position.Y.Offset + (input.Position - input.Position).Y))
    local _ = fenv.djqLRElUDgnWw
end)
local onInputEnded = UserInputService.InputEnded:Connect(function(input, gameProcessed)
    local _ = fenv.SYukuYEK6ruo
end)
local onClick = button.MouseButton1Click:Connect(function()
    local rotationTween = TweenService:Create(button, TweenInfo.new(0.35, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {Rotation = button.Rotation + 360})
    rotationTween:Play()
    label.Visible = false
    button.Text = "+"
    local udim2 = TweenService:Create(frame, TweenInfo.new(0.2, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {Size = UDim2.new(0, 260, 0, 45)})
    local _v550194 = udim2:Play()
    local _ = fenv.xdbZFmd9vqBT
end)
local onClick = button.MouseButton1Click:Connect(function()
    local udim2 = TweenService:Create(frame, TweenInfo.new(0.2, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {Size = UDim2.new(0, 0, 0, 0)})
    local _v550195 = udim2:Play()
    task.wait(0.2)
    local _v550196 = gui:Destroy()
    local _ = fenv.bJu4pNNf57Iq
end)
frame.Size = UDim2.new(0, 0, 0, 0)
local _v9 = TweenService:Create(frame, TweenInfo.new(0.35, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {Size = frame.Size})
local _ = fenv.Fadv0a38qEyx
local _v10 = _v9:Play()
